spring:
  application:
    name: priceservice

  datasource:
    url: jdbc:h2:mem:pricesdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always